services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dpark_app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - vendor_data:/var/www/vendor
    env_file:
      - .env

volumes:
  vendor_data: